### ISSUE TITLE
Add pinax-metrics (metron)

### ISSUE THREAD

**Issue by paltman** [pinax/blog.pinaxproject.com#1]

**Comment by ossanna16** [comment]
Do you think this would be a good issue for someone wanting to start contributing to Pinax?

**Comment by KatherineMichel** [comment]
Closing issue. This appears to have been done using metron. https://github.com/pinax/blog.pinaxproject.com/commit/ed53bbe6fc44dcf0fff76ac81c820b04e36a2dba#diff-b4ef698db8ca845e5845c4618278f29a
